// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/usuarios": {
    params: {};
  };
  "/logs": {
    params: {};
  };
  "/configuracoes": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/usuarios" | "/logs" | "/configuracoes";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/usuarios" | "/logs" | "/configuracoes";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/usuarios.tsx": {
    id: "routes/usuarios";
    page: "/usuarios";
  };
  "routes/logs.tsx": {
    id: "routes/logs";
    page: "/logs";
  };
  "routes/configuracoes.tsx": {
    id: "routes/configuracoes";
    page: "/configuracoes";
  };
};